Integration specs for views and fix n+1 problems
Jawad-Nazari/Blog-App pull request #8
Opened 2023-08-01 11:10 UTC by Jawad-Nazari

### In this PR, I have done the following:

- Solved N+1 problem when fetching all posts and their comments for a user without using the bullet gem

- Used Capybara to write integration tests for each view of the Blog App project according to the [requirements]

- Implemented tests for user index page, user show page, post index page and post show page

### Befor Fix
![Before Fix-1](https://github.com/Jawad-Nazari/Blog-App/assets/115032263/5ae3ee6e-3e0f-4a61-bb9f-a2f161caaa5e)
![Before Fix -2](https://github.com/Jawad-Nazari/Blog-App/assets/115032263/d623d924-4647-42da-bfb7-04d706574100)

### After Fix
![After Fix](https://github.com/Jawad-Nazari/Blog-App/assets/115032263/7ef1987a-a65a-4099-80c3-81ca16fcfb80)

2023-08-01 12:18 UTC, mckent05 requested changes
Hi @Jawad-Nazari, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Good job adding integration tests to your application 👏 👏 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 12:18 UTC, mckent05 commented on spec/integration/integration_specs.rb
> +    visit(user_posts_path(@user.id))
- Good job done so far, but according to the project requirements, please include a test that asserts you can see the first comments on a post. I suggest that you use the `five_recent_comments` in the post model for this. Please fix this 🙏

2023-08-01 12:18 UTC, mckent05 commented on spec/integration/integration_specs.rb
> +end
- You have done well so far, but please include all tests for the `posts#show` page, please do this according to the project requirements.

2023-08-01 12:18 UTC, mckent05 commented on spec/integration/integration_specs.rb
> +end
- You have done well so far, but according to the project requirements, each integration view test should have its own spec file, this would help make your test easier to understand. I.e The `user#index` file should have it's own single file e.t.c. Please fix this and ensure all tests pass 🙏

2023-08-02 06:57 UTC, Jawad-Nazari commented on spec/integration/integration_specs.rb
> +end
Hi @mckent05 
Thanks for your time and for reviewing our code. We will come up with a solution. 🙏

2023-08-02 07:29 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @Daniel-Kigozi 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 07:29 UTC, tresorsawasawa commented on spec/integration/post_index_spec.rb
> +      # @post = Post.create(title: 'First Post', text: 'This is my first post', author_id: @user.id)
- [ ] Good job trying to fix changes mentioned by the previous reviewer. However, while fixing those changes, I noticed that you leave some commented code lines in your your code base. For best practices and clean code reasons, kindly ensure that you remove all the commented and unused code lines from your code base.

2023-08-02 07:37 UTC, Jawad-Nazari commented on spec/integration/post_index_spec.rb
> +      # @post = Post.create(title: 'First Post', text: 'This is my first post', author_id: @user.id)
Hi @tresorsawasawa 
Thanks for your advice. I have removed the comment to make the code more readable.

2023-08-02 07:55 UTC, vickymarz approved these changes
Hi @Jawad-Nazari , 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Requested change implemented ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 08:01 UTC, merged